### ISSUE TITLE
pod too many restarts

### ISSUE THREAD

**Issue by GounGG** [k8spacket/k8spacket#11]
the pod will restart frequently, I have tried to adjust the timeout of prod, but it still can't solve the problem
![image](https://user-images.githubusercontent.com/17611638/196582846-e396c827-1dd2-4efd-8ff6-1257cc5f6e17.png)

![image](https://user-images.githubusercontent.com/17611638/196583002-4fe72135-3aa7-4094-b892-f30b54cb8888.png)

**Comment by k8spacket** [comment]
@GounGG 
I need more info.

Could you share k8spacket's logs and daemonset resource details? 
```
kubectl -n k8spacket logs <<pod_instance>>
kubectl -n k8spacket describe daemonsets.apps k8spacket
```

Does this situation happen directly following the start of k8spacket or after some time?

**Comment by k8spacket** [comment]
@GounGG 
Over 10 days without an answer.

I'm going to close this issue. If you would like to reopen it with more info, feel free.
