### ISSUE TITLE
Cannot import grafana dashboard for TLS connections chart

### ISSUE THREAD

**Issue by akramwaseem** [k8spacket/k8spacket#19]
I am not using grafana stack, creating config maps for this doesn't work for me.
I tried to just use the json for import TLS connections graph.

Seems like I am unable to import it, no matter I try it manually or via API or just copy paste the json.
Any suggestions? By default Data source goes to Prometheus but after changing it o json all queries are lost.

![image](https://user-images.githubusercontent.com/15903405/210883037-d94a2a18-0b92-418a-af81-4a987f3ca9f2.png)

![image](https://user-images.githubusercontent.com/15903405/210883083-8a4fd491-d97d-405a-9f1f-0344724b5635.png)

When I use explore option and pass all the values manully it works

![image](https://user-images.githubusercontent.com/15903405/210883443-be0b7808-8979-4863-aeec-d9d07060ef59.png)

**Comment by k8spacket** [comment]
Hi @akramwaseem 
Your issue is similar to #18 
Fixed in #21 

Try to pull the new master version and install dashboards one more time:
```
kubectl -n $GRAFANA_NS apply --recursive -f ./dashboards
```

**Comment by k8spacket** [comment]
@akramwaseem 
This thread is inactive for 10 days.

I'm going to close this issue.
