### ISSUE TITLE
configurable listening port

### ISSUE THREAD

**Issue by shokohsc** [k8spacket/k8spacket#2]
Hello, any chance port will be configurable in the future ?

**Comment by k8spacket** [comment]
Which one port? 8080?

Anyway, it is an open-source tool and you can suggest a change by pull request 👍

**Comment by shokohsc** [comment]
Yup, exactly that one, I don't know golang but glad to know it's open to PRs

**Comment by k8spacket** [comment]
@shokohsc 
configurable listener port is done (PR: https://github.com/k8spacket/k8spacket/pull/7 & PR: https://github.com/k8spacket/k8spacket-helm-chart/pull/7)

Please check it and continue this issue with your problems (e.g., `cap_net_admin=ep` if it still exists)

**Comment by shokohsc** [comment]
@k8spacket i can now use and configure k8spacket listening port through the helm chart, thanks
