### ISSUE TITLE
getting 404 error for /nodegraph path

### ISSUE THREAD

**Issue by rahul70422** [k8spacket/k8spacket#20]
getting 404 error for /nodegraph path

**Comment by k8spacket** [comment]
Hi @rahul70422 
I don't have enough information to give you a specific answer.
I assume your problem could be connected with this one: https://github.com/k8spacket/k8spacket/issues/15

**Comment by k8spacket** [comment]
@rahul70422 
This thread is inactive for 10 days.

I'm going to close this issue.
