### ISSUE TITLE
k8spacket提示Not Found

### ISSUE THREAD

**Issue by shendingjun** [k8spacket/k8spacket#29]
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/52272899/221479462-e4f56753-b00c-4cd9-8db7-69c0b3406948.png">
一个pod日志如下:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/52272899/221479538-3dd0a29b-eb5f-48fc-a830-908c0be7e202.png">
另一个pod日志如下:
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/52272899/221479585-9d32fa53-787a-492d-a3f7-107c9f9d6edf.png">

URL填的是http://k8spacket.k8spacket.svc.cluster.local:8080/nodegraph
，但是点击test，提示not found 404，请问是什么原因啊？k8spacket和grafana pod都正常运行。Prometheus metrics指标也有结果。

**Comment by k8spacket** [comment]
Hi @shendingjun 

As is written on the plugin page here: https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/ (part `Health`), the path `/api/health` is used during the save & test plugin.

Can you check the response on this endpoint using this command:
```
k -n k8spacket exec -it <<pod_name>> -c k8spacket -- wget -q -O- -S http://127.0.0.1:6676/nodegraph/api/health
```
Should be:
```
  HTTP/1.1 200 OK
  Date: Mon, 27 Feb 2023 09:37:37 GMT
  Content-Length: 0
  Connection: close
```

Additionally, check if the service was created properly:
```
k -n k8spacket get svc
```
Should be:
```
NAME          TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)      AGE
k8spacket   ClusterIP     some-ip            <none>             8080/TCP   4d15h
```

**Comment by shendingjun** [comment]
原来有些pod初始化失败了，连不上github。这个可以改成初始化失败，就整个pod失败，不要让他继续往下走，这样应该就不会误判？

**Comment by shendingjun** [comment]
> Hi @shendingjun
> 
> As is written on the plugin page here: https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/ (part `Health`), the path `/api/health` is used during the save & test plugin.
> 
> Can you check the response on this endpoint using this command:
> 
> ```
> k -n k8spacket exec -it <<pod_name>> -c k8spacket -- wget -q -O- -S http://127.0.0.1:6676/nodegraph/api/health
> ```
> 
> Should be:
> 
> ```
>   HTTP/1.1 200 OK
>   Date: Mon, 27 Feb 2023 09:37:37 GMT
>   Content-Length: 0
>   Connection: close
> ```
> 
> Additionally, check if the service was created properly:
> 
> ```
> k -n k8spacket get svc
> ```
> 
> Should be:
> 
> ```
> NAME          TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)      AGE
> k8spacket   ClusterIP     some-ip            <none>             8080/TCP   4d15h
> ```
原来有些pod初始化失败了，连不上github。这个可以改成初始化失败，就整个pod失败，不要让他继续往下走，这样应该就不会误判？

**Comment by k8spacket** [comment]
Hi @shendingjun 
It's a good idea. I will add it in the next version. Thanks for your feedback.
