### ISSUE TITLE
Suggestion - Update to README

### ISSUE THREAD

**Issue by tlb1galaxy** [k8spacket/k8spacket#30]
I think this tool has very good potential and really liking it so far.

I found the instructions (especially the install/setup) to be lacking for newbies (like me).
I have added some steps that might help newer K8s users to get this installed and operational.

Thanks for all the hard work.
[k8spacket-readme-suggestions.txt](https://github.com/k8spacket/k8spacket/files/10936265/k8spacket-readme-suggestions.txt)

**Comment by tlb1galaxy** [comment]
Had a syntax typo in the previous version.
[k8spacket-readme-suggestions.txt](https://github.com/k8spacket/k8spacket/files/10942497/k8spacket-readme-suggestions.txt)

**Comment by k8spacket** [comment]
Hi @tlb1galaxy 

Thanks for your great job on these suggestions. 
I'm going to use them soon.

**Comment by k8spacket** [comment]
Hi @tlb1galaxy 

I'm going to close this issue.
I'll use your suggestions with the next version release.

Thanks.
