### ISSUE TITLE
JSON API: Not Found

### ISSUE THREAD

**Issue by arezvani** [k8spacket/k8spacket#33]
I use helm to install k8spacket but when I want to add JSON API datasource I get this error:
JSON API: Not Found

I use http://k8spacket.k8spacket.svc.cluster.local:8080/tlsparser/api/data as URL.
With curl has response code 301 Moved Permanently and with wget I can download the data.

**Comment by arezvani** [comment]
It was from grafana bug. I delete datasource then create that it works successfully.

**Comment by k8spacket** [comment]
Hi @arezvani 

It wasn't a Grafana bug probably. There was a problem with that dashboard and it is fixed. See a similar issue here: https://github.com/k8spacket/k8spacket/issues/31#issuecomment-1465290875
