### ISSUE TITLE
Monitor External traffic of pod

### ISSUE THREAD

**Issue by arezvani** [k8spacket/k8spacket#34]
Hi, I want to monitor external transmit and receive traffics of pod. External traffic means traffic that send or receive from outside of k8s cluster.
Can you help me please?

**Comment by k8spacket** [comment]
Hi @arezvani 
What exactly do you want to monitor from the outside? You can monitor this traffic already.

## To the outside

Test it with curl from the cluster:
```
kubectl -n k8spacket run -it --rm --image=curlimages/curl curly -- sh

/ $ curl https://google.com
/ $ curl https://github.com
/ $ curl https://stackoverflow.com
```
Result:

![image](https://user-images.githubusercontent.com/95187481/230655305-64a969fc-7696-4c4d-94f2-15648404c2a6.png)

![image](https://user-images.githubusercontent.com/95187481/230655343-49c70530-c5d6-4a06-866c-f2207645c3c1.png)

![image](https://user-images.githubusercontent.com/95187481/230655362-36190bc1-9a4b-4c73-a910-9dce0566aa48.png)


## From the outside

I use `istio-ingressgateway` as an ingress in the cluster. Hit it from the outside gives me results with the graph:

![image](https://user-images.githubusercontent.com/95187481/230656202-6a63a53e-7c72-49c5-bb76-3a416cec0773.png)

**Comment by k8spacket** [comment]
Hi @arezvani 

I'm going to close this issue. 
If you have more questions feel free to reopen it.
