### ISSUE TITLE
Is there a way to identify traffic which is not encrypted?

### ISSUE THREAD

**Issue by justinas-b** [k8spacket/k8spacket#35]
Hey there! using this tool I can list all traffic and then there is a dedicated metric for all TLS traffic. What i am trying to achieve - I would like to easily identify all traffic within cluster which is not encrypted.

Would it be possible to have a dedicated metric for plaintext traffic? Or maybe there is already a way to do so?

**Comment by k8spacket** [comment]
Hi @justinas-b 

I'm going to close this issue.
If you have more questions feel free to reopen it.
