### ISSUE TITLE
its not respecting time filter .. 

### ISSUE THREAD

**Issue by shukla2009** [k8spacket/k8spacket#4]
As of now connection graph show all connection regardless of the time selected.

**Comment by k8spacket** [comment]
@shukla2009 
Node Graph Panel (https://grafana.com/docs/grafana/latest/visualizations/node-graph/) is not able to use Prometheus datasource. k8spacket exposes metrics and uses Node Graph API (https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/) to visualize traffic. 
For now, k8spacket shows a projection of all collected connections. Time range controls are ignored.
