### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by zzl221000** [k8spacket/k8spacket#44]
This error occurs after about 2 minutes of running the program.
```
2024/02/28 13:53:01 [nodegraph plugin] Connection: src=10.42.0.133 srcName=service-info-68744b99bd-6g88q srcPort=49444 srcNS=defaultdst=121.226.36.81 dstName= dstPort=4337 dstNS= closed=true bytesSent=1354 bytesReceived=649 duration=0.134677404
fatal error: concurrent map writes
```
---
k8spacket version: 1.2.1
k8s version: 1.21

**Comment by k8spacket** [comment]
Hi @zzl221000 

Version < `2.0.0` uses a global map to keep connection items indeed and this causes the problem (although used sync.RWMutex lock).

In version `2.0.0` k8spacket uses the `bbolt` KV database with transactions and this is concurrency-safe

Are you able to use version `2.0.0`? 
It's faster, better, more efficient. Remember about the limitation - Linux kernel >= 5.8

**Comment by zzl221000** [comment]
> Linux kernel >= 5.8

All of our machines have linux kernel version 4.18, so it looks like we'll have to give up on k8spacket

**Comment by k8spacket** [comment]
Hi @zzl221000 
It's a good idea to upgrade the kernel version. 4.18 had EOL in 2018. 
It sounds like a win-win option - better security and the possibility to try `k8spacket` 😉 

I'm going to close this issue.
If you have more questions feel free to reopen it.
