### ISSUE TITLE
Provide krew plugin?

### ISSUE THREAD

**Issue by joebowbeer** [k8spacket/k8spacket#50]
Would it make sense to provide a krew plugin so this could be used via kubectl?

**Comment by k8spacket** [comment]
Hi @joebowbeer 
What would you like to get as a response to run that plugin in a shell? 
I can imagine getting information about TLS metadata, but drawing a node graph about TCP connections may be difficult.

As far as I understand, your vision is to be non-addicted to the Grafana stack.

**Comment by k8spacket** [comment]
I don't see the big value of using a dedicated cli tool with k8spacket.
