### ISSUE TITLE
Can not find plugins

### ISSUE THREAD

**Issue by alexandersperling** [k8spacket/k8spacket#51]
When deploying k8spacket in our cluster its not able to find the needed plugins, however they are available in the `plugins` directory

I'm getting this error message

```
2024/03/27 12:58:02 [k8spacket] [plugins] Cannot find plugin TLSConsumerPlugin, gave up. plugin: symbol TLSConsumerPlugin not found in plugin github.com/k8spacket/plugins/nodegraph
2024/03/27 12:58:02 [k8spacket] [plugins] Cannot find plugin TCPConsumerPlugin, gave up. plugin: symbol TCPConsumerPlugin not found in plugin github.com/k8spacket/plugins/tls-parser
```

When moving the plugins into the directory where the k8spacket binary lives, I wont get this message. However the application fails to start up with the following error.

```
2024/03/27 13:29:27 [k8spacket] [api] Serving requests on port 6676
2024/03/27 13:29:27 [k8spacket] INIT inet
2024/03/27 13:29:27 [k8spacket] [inet] Cannot attach tracepoint: neither debugfs nor tracefs are mounted
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e3e94f]

goroutine 8 [running]:
github.com/k8spacket/k8spacket/ebpf/inet.Init()
	/home/k8spacket/ebpf/inet/inet.go:54 +0x1af
created by github.com/k8spacket/k8spacket/ebpf.LoadEbpf in goroutine 1
	/home/k8spacket/ebpf/loader.go:20 +0x1a

```

What might be the problem here?

System:

AWS EKS
AmazonLinux 2
Deployed with helm

**Comment by k8spacket** [comment]
Additionally, what version of Linux kernel is there on your AmazonLinux VMs? 
Remember about the limitation kernel version >= 5.8

**Comment by alexandersperling** [comment]
Will try to change this.

And we are using 5.10

**Comment by alexandersperling** [comment]
Tried to change the volume mounts and now I'm getting the following error.

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to s │
│ tart container process: error during container init: error mounting "/sys/kernel/debug/tracing" to rootfs at "/sys/kernel/debug/tracing": mkdir /run/containerd/io.containerd.runtime.v2.task/k8s │
│ .io/k8spacket/rootfs/sys/kernel/debug/tracing: no such file or directory: unknown  
```

when checking the instance itself, the directory is available

**Comment by k8spacket** [comment]
Ok, my fault.
The path mounted from the node should be `/sys/kernel/debug/tracing`, but the container should see it on the path: `/sys/kernel/tracing`

It should look like:
```
spec:
  template:
    spec:
      containers:
. . .
        volumeMounts:
. . .
        - mountPath: /sys/kernel/tracing
          name: tracing
      volumes:
. . .
      - hostPath:
          path: /sys/kernel/debug/tracing
          type: ""
        name: tracing
```

**Comment by alexandersperling** [comment]
Thanks, that fixed it.

I'm playing around currently with that tool, but when we want to use this in some more automated way, I will need to find a way to configure those values.

Are you open that I should open an PR for that?

**Comment by k8spacket** [comment]
Of course.
It is a great idea to add `volumes` and `volumeMounts` to `values.yaml`.

**Comment by muhammad-asn** [comment]
Thank you for this

**Comment by alexandersperling** [comment]
Thanks for the support. This works now.
