### ISSUE TITLE
pods in crash loop while installing with helm chart

### ISSUE THREAD

**Issue by saireddyb-digite** [k8spacket/k8spacket#55]
helm install k8spacket --namespace dev k8spacket/k8spacket 

kubectl  logs k8spacket-pqvrp -n dev -f
Defaulted container "k8spacket" out of: k8spacket, init-k8spacket (init)
2024/06/05 10:34:33 [k8spacket] [plugins] Cannot find plugin TLSConsumerPlugin, gave up. plugin: symbol TLSConsumerPlugin not found in plugin github.com/k8spacket/plugins/nodegraph
2024/06/05 10:34:33 [k8spacket] [plugins] Cannot find plugin TCPConsumerPlugin, gave up. plugin: symbol TCPConsumerPlugin not found in plugin github.com/k8spacket/plugins/tls-parser
2024/06/05 10:34:33 [k8spacket] [api] Serving requests on port 6676
2024/06/05 10:34:33 [k8spacket] INIT inet
2024/06/05 10:34:34 [k8spacket] [inet] Cannot attach tracepoint: neither debugfs nor tracefs are mounted
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f5320f]

goroutine 28 [running]:
github.com/k8spacket/k8spacket/ebpf/inet.Init()
	/home/k8spacket/ebpf/inet/inet.go:54 +0x1cf
created by github.com/k8spacket/k8spacket/ebpf.LoadEbpf in goroutine 1
	/home/k8spacket/ebpf/loader.go:20 +0x1a

**Comment by bareckidarek** [comment]
Hi @saireddyb-digite 

See the thread here: https://github.com/k8spacket/k8spacket/issues/51

Are you using AWS EKS Amazon Linux 2 OS?

See the hint in `values.yaml` https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/values.yaml#L99

**Comment by saireddyb-digite** [comment]
@bareckidarek Thanks it worked.
