### ISSUE TITLE
Why used hostPort in pod of daemonset?

### ISSUE THREAD

**Issue by sober-wang** [k8spacket/k8spacket#6]
![图片](https://user-images.githubusercontent.com/35804630/185275408-a4dc17f8-0ec1-458a-905b-b08df810e9a6.png)

Why don't used k8s clouster network ?

mybe, the monitor message direction is this:
```
user --> k8s ingress-controller
                    |--> grafana                                     
                              |---> k8spackage service 
                                           |--> k8spacket pod 2
                                           |--> k8spacket pod 3
                                           |--> k8spacket pod 1
```

**Comment by k8spacket** [comment]
@sober-wang 
k8spacket doesn't use `hostPort` directly. 

<img width="750" alt="Screenshot 2022-08-18 at 08 51 50 1" src="https://user-images.githubusercontent.com/95187481/185467916-d0be168c-e56d-42ef-abcd-7d445ff00b64.png">

check here: https://github.com/k8spacket/k8spacket-helm-chart/blob/master/templates/daemonset.yaml

But, daemonset must have `hostNetwork:true` to be able to reach network interfaces on the host. This could be a problem when port 8080 (default k8spacket listener port) is exposed as `hostPort` or `NodePort` in the cluster already.  This port should be configurable which will be done soon.

Why did your cluster set this field `hostPort: 8080`? Did you use the default helm configuration from this repo https://github.com/k8spacket/k8spacket-helm-chart ?

**Comment by k8spacket** [comment]
@sober-wang 
The listener port is configurable now. See the new version of the helm chart: https://github.com/k8spacket/k8spacket-helm-chart/blob/master/values.yaml#L49

Default now is 6676

**Comment by sober-wang** [comment]
Thanks.
