### ISSUE TITLE
k8spacket pod going to crashloopbackoff

### ISSUE THREAD

**Issue by ajayanaj** [k8spacket/k8spacket#61]
Hello,

I'm trying to install k8spacket by following the helm installation steps, after the helm installation the pods are not coming and it's going into "CrashLoopbackoff" state with the below error.
`2024/07/09 08:02:50 [k8spacket] [inet] Cannot attach tracepoint: neither debugfs nor tracefs are mounted
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f5280f]

goroutine 30 [running]:
github.com/k8spacket/k8spacket/ebpf/inet.Init()
	/home/k8spacket/ebpf/inet/inet.go:54 +0x1cf
created by github.com/k8spacket/k8spacket/ebpf.LoadEbpf in goroutine 1
	/home/k8spacket/ebpf/loader.go:20 +0x1a`
	
I couldn't figure out whats wrong with the configurations. Is there any prerequisites are there? 
I'm running the installation on EKS with below kernal version.
5.10.219-208.866.amzn2.x86_64

**Comment by k8spacket** [comment]
Hi @ajayanaj 

See the thread here: https://github.com/k8spacket/k8spacket/issues/51

Are you using AWS EKS Amazon Linux 2 OS?

See the hint in values.yaml https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/values.yaml#L99

**Comment by ajayanaj** [comment]
Go it, I changed the path to /sys/kernel/debug/tracing and it worked. 
Yes it is Linux OS 2
Thanks a lot for the quick response.
