### ISSUE TITLE
Pods go in to CrashLoopBackOff error after upgrading from 1.2.1 to 2.0.4

### ISSUE THREAD

**Issue by gjolps** [k8spacket/k8spacket#64]
Hi @k8spacket, 

I recently upgraded from 1.2.1 to 2.0.4 and noticed that few pods went CrashLoopBackOff as soon as k8spacket started sending out data with the below error - 

```
panic: runtime error: slice bounds out of range [:102] with length 100
 
goroutine 148 [running]:
github.com/k8spacket/k8spacket/ebpf/tc.distribute({0xafe7d53, 0xafedb5b, 0xaae4, 0x20f0, 0x303, 0x4, {0x0}, {0x304, 0x303, 0x2d, ...}, ...})
        /home/k8spacket/ebpf/tc/tc.go:146 +0x29e
github.com/k8spacket/k8spacket/ebpf/tc.Init.func1()
        /home/k8spacket/ebpf/tc/tc.go:97 +0x1b8
created by github.com/k8spacket/k8spacket/ebpf/tc.Init in goroutine 116
        /home/k8spacket/ebpf/tc/tc.go:77 +0x3fb
```

I updated tc.go as below and it solved the issue.

```
func distribute(event tcTlsHandshakeEvent) {
	
	tlsVersionsLen := int(event.TlsVersionsLength)/2
	if tlsVersionsLen > len(event.TlsVersions) {
        	tlsVersionsLen = len(event.TlsVersions)
    	}
	
		ciphersLen := int(event.CiphersLength)/2
	if ciphersLen > len(event.Ciphers) {
        	ciphersLen = len(event.Ciphers)
    	}
	
		serverNameLen := int(event.ServerNameLength)
	if serverNameLen > len(event.ServerName){
		serverNameLen = len(event.ServerName)
	}
	
	tlsEvent := plugin_api.TLSEvent{
		Client: plugin_api.Address{
			Addr: intToIP4(event.Saddr),
			Port: event.Sport},
		Server: plugin_api.Address{
			Addr: intToIP4(event.Daddr),
			Port: event.Dport},
		TlsVersions:    event.TlsVersions[:tlsVersionsLen],
		Ciphers:        event.Ciphers[:ciphersLen],
		ServerName:     string(event.ServerName[:serverNameLen]),
		UsedTlsVersion: event.UsedTlsVersion,
		UsedCipher:     event.UsedCipher}
	ebpf_tools.EnrichAddress(&tlsEvent.Client)
	ebpf_tools.EnrichAddress(&tlsEvent.Server)
	broker.TLSEvent(tlsEvent)
}

```

**Comment by k8spacket** [comment]
Hi @gjolps 

That's a weird situation 🤔 . Could you share the kernel version where it is running?
But your solution looks great, thanks for your contribution. Would you like to prepare PR with it?

**Comment by gjolps** [comment]
Hi, I'm running this on RHEL 9 having kernel version 5.14.
Have raised a PR for the same.

**Comment by gjolps** [comment]
hi @k8spacket , pods are restarting at random because of insufficient memory. All our nodes have 32Gb of Memory. 

```
    State:          Running
      Started:      Tue, 16 Jul 2024 14:36:38 -0400
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 16 Jul 2024 00:20:15 -0400
      Finished:     Tue, 16 Jul 2024 14:36:38 -0400
    Ready:          True
    Restart Count:  3
    Limits:
      cpu:     300m
      memory:  200Mi
    Requests:
      cpu:      50m
      memory:   100Mi
```

**Comment by gjolps** [comment]
hi @k8spacket , just an update, After doubling the Memory limits and requests, all pods restarted just once in the last 6 days. 
Have a request regarding the documentation of metrics. Could you please create one with some examples. I'm confused with the count and sum and how to use them.
Another request which I'd like to make is have a random connection id for every connection. Is that possible? I'm trying to create a panel containing having current active connection count and since when they have been active but I'm not able to join these 2 queries as joining them either on src or dst removes other connections having same src or dst names.
Thanks!

**Comment by k8spacket** [comment]
Hi @gjolps 

Doubling mem req and limit is ok. It is still less than the version without eBPF (like you had the previous 1.2.1 - https://github.com/k8spacket/k8spacket-helm-chart/blob/k8spacket-1.2.1/charts/k8spacket/values.yaml#L42)


> Have a request regarding the documentation of metrics. Could you please create one with some examples. I'm confused with the count and sum and how to use them.

sum and count belong to Prometheus summary metric type: https://prometheus.io/docs/concepts/metric_types/#summary, where f.e.:
- `k8s_packet_bytes_received_sum` is the total sum of received bytes from destination
- `k8s_packet_bytes_received_count` is the counter of calls to that destination

example:

- somewhere inside the cluster, I call 
```
curl https://8.8.8.8 -H "Connection:close"
``` 
- I use a container with `curlyimages/curl` like 
```
kubectl run -it --rm --image=curlimages/curl curly -- sh
```

- Then check metrics in the k8spacket endpoint `/metrics`
```
k8s_packet_bytes_received_sum{dst="8.8.8.8",dst_name="Google LLC",dst_port="443",ns="default",persistent="false",src="10.2.0.114",src_name="pod.curly",src_port="dynamic"} 5875
k8s_packet_bytes_received_count{dst="8.8.8.8",dst_name="Google LLC",dst_port="443",ns="default",persistent="false",src="10.2.0.114",src_name="pod.curly",src_port="dynamic"} 1
```
- As you can see, there was one call to destination `8.8.8.8` and we received 5875 bytes

- Next, I call a second time 
```
curl https://8.8.8.8 -H "Connection:close"
``` 
- Get:
```
k8s_packet_bytes_received_sum{dst="8.8.8.8",dst_name="Google LLC",dst_port="443",ns="default",persistent="false",src="10.2.0.114",src_name="pod.curly",src_port="dynamic"} 11750
k8s_packet_bytes_received_count{dst="8.8.8.8",dst_name="Google LLC",dst_port="443",ns="default",persistent="false",src="10.2.0.114",src_name="pod.curly",src_port="dynamic"} 2
```
Now a summary of received bytes is 11750 (from the first and second call) and there were 2 calls

Based on it, you can calculate f.e. average bytes received for each call `k8s_packet_bytes_received_sum / k8s_packet_bytes_received_count`


> Another request which I'd like to make is have a random connection id for every connection. Is that possible? I'm trying to create a panel containing having current active connection count and since when they have been active but I'm not able to join these 2 queries as joining them either on src or dst removes other connections having same src or dst names.

You can use src and dst, but not names only. You have to add src_port and dst_port for the identification. In default mode, k8spacket hides `src_port` (https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/values.yaml#L85) to reduce a cardinality of Prometheus metrics. You can change this property and see how it works for you.

**Comment by k8spacket** [comment]
@gjolps I'm going to close this issue. Thanks for your PR. It's merged.
