### ISSUE TITLE
Some Kubernetes pods have their name/namespace set to "N/A"

### ISSUE THREAD

**Issue by Lawouach** [k8spacket/k8spacket#76]
Hi,

Thank you for an awesome tool!

I'm running it in a local microk8s. I've deployed the Open Telemetry demo into it as-is.

For some reasons, some pods have their name and namespace set to "N/A" and I can't figure out why. I don't see any difference between them and pods which have the correct info set.

For instance:

```json
  {
    "src": "10.1.210.154",
    "srcName": "N/A",
    "srcNamespace": "",
    "dst": "10.1.210.150",
    "dstName": "pod.otel-demo-otelcol-5d8968b776-t9jdd",
    "dstNamespace": "default",
    "connCount": 207,
    "connPersistent": 0,
    "bytesSent": 11262137,
    "bytesReceived": 63897,
    "duration": 338061,
    "maxDuration": 2778,
    "lastSeen": "2024-10-13T19:34:57.0283475Z"
  },
```

This reflects the following pod:

```
Name:             otel-demo-loadgenerator-6689d8dc75-wfr4x
Namespace:        default
Priority:         0
Service Account:  otel-demo
Node:             sylvain-home/192.168.1.28
Start Time:       Sun, 13 Oct 2024 18:34:10 +0200
Labels:           app.kubernetes.io/component=loadgenerator
                  app.kubernetes.io/instance=otel-demo
                  app.kubernetes.io/name=otel-demo-loadgenerator
                  opentelemetry.io/name=otel-demo-loadgenerator
                  pod-template-hash=6689d8dc75
Annotations:      cni.projectcalico.org/containerID: d51a4b7bd6e3077738b4f4c65a824b7dd0270031f76d8bf4373131d9f0d557e8
                  cni.projectcalico.org/podIP: 10.1.210.154/32
                  cni.projectcalico.org/podIPs: 10.1.210.154/32
Status:           Running
IP:               10.1.210.154
IPs:
  IP:           10.1.210.154
Controlled By:  ReplicaSet/otel-demo-loadgenerator-6689d8dc75
Containers:
  loadgenerator:
    Container ID:   containerd://9c5bbf747fa0bc42c70a48969a1c2f8a179f82d23c22e8c7121b6fa68985c513
    Image:          ghcr.io/open-telemetry/demo:1.11.1-loadgenerator
    Image ID:       ghcr.io/open-telemetry/demo@sha256:a95db305b4d0866b6637af1a45cc5b62355782d31c219b48360f104f43590c1e
    Port:           8089/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sun, 13 Oct 2024 18:37:08 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  1Gi
    Requests:
      memory:  1Gi
    Environment:
      OTEL_SERVICE_NAME:                                   (v1:metadata.labels['app.kubernetes.io/component'])
      OTEL_COLLECTOR_NAME:                                otel-demo-otelcol
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE:  cumulative
      LOCUST_WEB_PORT:                                    8089
      LOCUST_USERS:                                       10
      LOCUST_SPAWN_RATE:                                  1
      LOCUST_HOST:                                        http://otel-demo-frontendproxy:8080
      LOCUST_HEADLESS:                                    false
      LOCUST_AUTOSTART:                                   true
      LOCUST_BROWSER_TRAFFIC_ENABLED:                     true
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION:             python
      FLAGD_HOST:                                         otel-demo-flagd
      FLAGD_PORT:                                         8013
      OTEL_EXPORTER_OTLP_ENDPOINT:                        http://$(OTEL_COLLECTOR_NAME):4317
      OTEL_RESOURCE_ATTRIBUTES:                           service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.11.1
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7qbhs (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  kube-api-access-7qbhs:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>

```

I've tried to go through the code but I'm not sure where the change might open.

**Comment by Lawouach** [comment]
Right, so interestingly, restarting the `k8spacket` pod did the trick. Now I see the data correctly.

My gut feeling could be as follows:

1. k8spacket was running before the demo
2. When I deployed the OTEL demo, some pods had failures that prevented the data to be correctly read somehow (crashloopbackoff migh interfere with k8spacket?)
3. I assume k8spacket has a cahce/internal db that it uses and since the IP of the pod had not changed, it didn't update the information about the pod.
4. When I restarted k8spacket, it refreshed and now it's all happy bunny.

Is that plausible?

**Comment by k8spacket** [comment]
Hi @Lawouach
Thanks for appreciation

This part of the code is responsible for getting new workload names and IPs: https://github.com/k8spacket/k8spacket/blob/master/ebpf/loader.go#L40-L64

There are some corner cases about this approach, but I don't remember them now. Your test might be a great starting point to recall problems. I will try to do it and be back here soon.

**Comment by Lawouach** [comment]
Thanks!

I appreciate you looking into this and hopefully it won't be a deep rabbit hole.

**Comment by k8spacket** [comment]
Ok @Lawouach, I think I know what happened here

As I shared in the last comment, the code from https://github.com/k8spacket/k8spacket/blob/master/ebpf/loader.go#L40-L64 works more or less like this:
- every `$K8S_PACKET_TCP_LISTENER_INTERFACES_REFRESH_PERIOD` (default 10 seconds (https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/values.yaml#L111)), check if there is a new network interface to listen (== if there is new workload(POD) in the cluster)
- if true, fetch K8S metadata info (map with key=IP, value=name and namespace of POD)

As I see in the comment https://github.com/k8spacket/k8spacket/issues/76#issue-2584221857, it took 3 minutes to start POD `otel-demo-loadgenerator-6689d8dc75-wfr4x`. I supposed during these 3 minutes, k8spacket refreshed listeners but didn't get the name and namespace of this POD because it wasn't ready. It didn't do it later, because there weren't any new interfaces to listen so no new fetching of K8S metadata was called. 

You restarted a k8spacket app, but running any new POD should help too, f.e. run curl pod
```
kubectl run -it --rm --image=curlimages/curl curly -- sh
```

I need to think about it because fetching K8S metadata while refreshing network interfaces is not the best option for now.

**Comment by k8spacket** [comment]
Hi @Lawouach 

There is a new k8spacket version available in helm (2.1.2)

The approach has been changed from calling k8s API to registering informers for getting events about newly created k8s resources: https://pkg.go.dev/k8s.io/client-go/informers

I hope it will fix the gap discovered in the last comment.
It'd be nice to get feedback from you.

**Comment by Lawouach** [comment]
Awesome! I'll give it a try rapidly.

**Comment by k8spacket** [comment]
Hi @Lawouach 
I will close this issue for now. Thanks for reporting that bug.

**Comment by Lawouach** [comment]
Hi @k8spacket that's the right call. I haven't had a chance to try it yet as I moved to a different project. But that is still on my dodo. I'll come back when I try.
