### ISSUE TITLE
Docker interface has no name associated with it

### ISSUE THREAD

**Issue by Lawouach** [k8spacket/k8spacket#77]
Hi there,

I've noticed this node in the nodegraph:

```json
{
              "id": "172.17.0.1",
              "title": "N/A",
              "subTitle": "172.17.0.1",
              "mainStat": "all: N/A",
              "secondaryStat": "persistent: N/A",
              "arc__1": 0,
              "arc__2": 0,
              "arc__3": 0
            },
```
It happens to be the docker bridge interface on the host:

```
docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:6f:38:04:78 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:6fff:fe38:478/64 scope link 
       valid_lft forever preferred_lft forever
```

Do you think it would be possible to lookup a name for it?

This is part of a more general challenge of dealing with nodes without a name, it makes the analysis challenging because the IP doesn't always make sense in a large context.

**Comment by k8spacket** [comment]
Hi @Lawouach 

The current implementation doesn't fetch this information and I don't have a plan to improve this part.
