### ISSUE TITLE
fail to run on openshift 4.8

### ISSUE THREAD

**Issue by tomer1983** [k8spacket/k8spacket#8]
Hi
after installing helm chart version 0.1.1
the pods cant start , regarding "standard_init_linux.go:219: exec user process caused: operation not permitted" errors on pods

is this app capable to run on openshift platform ?

**Comment by k8spacket** [comment]
@tomer1983 
There was a problem with missing `securityContext` capabilities (`NET_RAW`). After adding it, looks better:

<img src="https://user-images.githubusercontent.com/95187481/187214155-2736680e-225f-4bd6-9f64-185c3b5e2add.png">

I've added it to the current helm chart version (https://github.com/k8spacket/k8spacket-helm-chart/blob/master/values.yaml#L22), so what you need to do is update or install `k8spacket` by helm one more time.
