### ISSUE TITLE
Rquest Feature - total bandwith transfer / transaction 

### ISSUE THREAD

**Issue by mw-akbar** [k8spacket/k8spacket#84]
i hope in feature k8spacket have feature for monitoring total bandwith transfer for every connection in dashboard `k8spacket-tls-connections-dashboard`

**Comment by k8spacket** [comment]
Hi @mw-akbar 

Every row in the table on the dashboard `k8spacket-tls-connections-dashboard` doesn't correspond to exactly one TLS connection. If your workload calls the HTTPS address more than once, only one row will be in that dashboard.

Additionally, this dashboard is about TLS handshake metadata, but you can find a bandwidth in dashboard `k8spacket-node-graph-dashboard`

f.e.

- run a few curls to any https address (f.e. `https://www.cncf.io/`)
- find that row in `k8spacket-tls-connections-dashboard`
<img width="1865" alt="image" src="https://github.com/user-attachments/assets/dd8cab07-6aba-4f4b-81bb-40dafff12e3c">

- get `dst` IP, here `23.185.0.3`
- find that connection in `k8spacket-node-graph-dashboard` (`graph mode: bytes`, `include name: 23.185.0.3`)
<img width="1327" alt="image" src="https://github.com/user-attachments/assets/4de7efd7-339b-4355-a829-4188c306141b">

**Comment by k8spacket** [comment]
Hi @mw-akbar 
I'm going to close this issue because I don't plan to add bandwidth information on the TLS dashboard. 
If you have more questions, open it again or add a new ticket.
